import type { Metadata } from "next";
import { Inclusive_Sans, Tilt_Neon } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import "react-awesome-button/dist/styles.css";
import Parallax from "@/components/Parallax";
const inter = Tilt_Neon({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} md:pl-[145px] w-full relative`}>
        <Sidebar />
        <Parallax />
        {children}
      </body>
    </html>
  );
}
